service: lambda-flex-run

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  executeJob:
    handler: src/executeJob.executeJob
    events:
      - s3: lambda-flex-run-topics
      - eventBridge:
          schedule: rate(15 minutes)

plugins:
  - serverless-offline
  - serverless-openapi-documentation


