service: serverless-softek-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  executeJob:
    handler: src/executeJob.executeJob
    events:
      - s3: topics
      - eventBridge:
          schedule: rate(30 minutes)

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-openapi-documentation


